version: '3'

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
      - mysql
    networks:
      - proxy
      - default
    volumes:
      - ./src:/var/lib/nginx/html:ro
      - ./data/assets:/var/lib/nginx/assets:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:$XWL_WEB_HOST
      - traefik.port=80
      - traefik.enable=true

  php:
    image: jbenninghoff/php-xml-weblog
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: $XWL_MYSQL_PASSWORD
    volumes:
      - ./src:/var/lib/nginx/html:ro

  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $XWL_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: xml_weblog
      MYSQL_USER: weblog
      MYSQL_PASSWORD: $XWL_MYSQL_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql

  # phpmyadmin should only be used in a dev environment
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - proxy
      - default
    environment:
      # PMA_HOST defaults to 'db'
      PMA_HOST: mysql
    labels:
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:$XWL_PMA_HOST
      - traefik.port=80
      - traefik.enable=true

networks:
  proxy:
    external: true
