version: '3'

services:
  web:
    image: nginx:alpine
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/lib/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    image: php:5-fpm-alpine
    volumes:
      - ./src:/var/lib/nginx/html:ro
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - ./data/mysql:/var/lib/mysql

  # temporarily include phpmyadmin for testing
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      # PMA_HOST defaults to 'db'
      PMA_HOST: mysql
