version: '3'

services:
  web:
    image: nginx:alpine
    depends_on:
      - php
      - mysql
    ports:
      - $XWL_WEB_PORT:80
    volumes:
      - ./src:/var/lib/nginx/html:ro
      - ./data/assets:/var/lib/nginx/assets:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    image: jbenninghoff/php-xml-weblog
    environment:
      MYSQL_ROOT_PASSWORD: $XWL_MYSQL_PASSWORD
    volumes:
      - ./src:/var/lib/nginx/html:ro
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $XWL_MYSQL_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql

  # temporarily include phpmyadmin for testing
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - $XWL_PMA_PORT:80
    environment:
      # PMA_HOST defaults to 'db'
      PMA_HOST: mysql
