version: '3'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.toml:/traefik.toml:ro
      - ./data/acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:$TRAEFIK_HOST
      - traefik.port=8080
      - traefik.enable=true

networks:
  public:
    external: true
