defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:my-encrypted-htpasswd"]

[docker]
exposedbydefault = false
