defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[web]
address = ":8080"
readOnly = true
  [web.auth.basic]
  users = ["admin:my-encrypted-htpasswd"]

[acme]
email = "my-email"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

[docker]
exposedbydefault = false
