defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:my-encrypted-htpasswd"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "technomagik.net"
watch = true
exposedbydefault = false
